Add link icon to anchor link headings
10up/Engineering-Best-Practices pull request #278
Opened 2019-01-15 14:46 UTC by colorful-tones

Fixes #209 

I used the existing IcoMoon `selection.json` and added the link icon to the set. I then used a pseudo-element to put an icon next to each `.anchor-heading` (existing class).

Demonstration screenshot of ending result:
![screenshot 2019-01-15 09 43 53](https://user-images.githubusercontent.com/405912/51187710-659ff700-18aa-11e9-96f0-19d10b412d69.png)

2019-01-15 15:59 UTC, timwright12 requested changes

2019-01-15 15:59 UTC, timwright12 commented on _includes/_sass/includes/_docs-section.scss
> +		&::after {
Sorry, can you make this a clickable element in the DOM? We want to be able to click the icon so the user can get the sharable URL

2019-01-15 18:30 UTC, colorful-tones commented
I added a new Liquid Template partial, which accepts an `anchor="foo"` argument. This is used to output the anchor link in each template.

I then added the call with appropriate anchor link to each heading section, on each page. I then tested each page to verify that anchor links were matching.

Attaching Gif of resulting treatment:
![10upengineering-anchor-links](https://user-images.githubusercontent.com/405912/51201285-a824fc00-18c9-11e9-9a11-2d347a46424f.gif)

2019-01-18 14:31 UTC, timwright12 requested changes
A few thing here:
**1. Let's bring back the link icon by default so people know you can link to the heading without hovering**

<img width="900" alt="screen shot 2019-01-18 at 9 25 50 am" src="https://user-images.githubusercontent.com/459581/51392507-3c2dd800-1b03-11e9-8847-d960028858b1.png">

**2. On the actual hash, let's make sure it aligns with the "back to top" link (we can just align all 3 items to the baseline of the heading text) and sync those font sizes (make the hash smaller). Also we'll want the link icon to be center aligned with the hash text.**

<img width="782" alt="screen shot 2019-01-18 at 9 23 05 am" src="https://user-images.githubusercontent.com/459581/51392620-99c22480-1b03-11e9-8849-202b9bdd8f9b.png">

**3. Check all your screen sizes to make sure we don't get weird breaks between the hash text and the back to top (I know this is dependent on the hash length, but let's do our best)**
 
<img width="690" alt="screen shot 2019-01-18 at 9 22 50 am" src="https://user-images.githubusercontent.com/459581/51392663-c2e2b500-1b03-11e9-891f-4bc5c64eb55d.png">
<img width="541" alt="screen shot 2019-01-18 at 9 22 36 am" src="https://user-images.githubusercontent.com/459581/51392673-c83fff80-1b03-11e9-9e68-5d0b55c05bd4.png">

**4. Make sure the hash can be exposed on focus as well as hover for keyboard users.**

2019-01-22 15:22 UTC, timwright12 requested changes
@colorful-tones 
**Visual**:
Lets enlarge the link icon to 1em x 1em, then center it vertically and remove the opacity so the color contrast doesn't dip below our accessibility standards.

**Interaction**:
The default state of the heading should be: [heading] [link icon] [back to top]
On hover and/or focus of the [link icon], display the [#hash] as well to make it: [heading] [#hash] [link icon] [back to top]

2019-02-08 16:42 UTC, colorful-tones commented
> **Visual**:
Lets enlarge the link icon to 1em x 1em, then center it vertically and remove the opacity so the color contrast doesn't dip below our accessibility standards.

These changes have been implemented.

> **Interaction**:
The default state of the heading should be: [heading] [link icon] [back to top]
On hover and/or focus of the [link icon], display the [#hash] as well to make it: [heading] [#hash] [link icon] [back to top]

These changes have been implemented.

Gif of current appearance and outcome:
![anchor-link](https://user-images.githubusercontent.com/405912/52492137-9831cc80-2b96-11e9-88ba-18f2daa85f98.gif)

2019-02-08 16:42 UTC, colorful-tones commented
Tagging @timwright12 for review please.

2019-03-01 13:50 UTC, timwright12 approved these changes

2019-03-01 13:50 UTC, merged