Add Gutenberg react and framing discussion points.
10up/Engineering-Best-Practices pull request #312
Opened 2019-09-12 14:47 UTC by magnificode

### Description of the Change

This PR brings in Gutenberg documentation from the FEE exploration of Gutenberg. Specifically touching on React's role in Gutenberg, as well as how Gutenberg should be framed as a supplementary tool for publishers.

### Checklist:
- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests passed.

2019-09-12 15:00 UTC, timwright12 requested changes

2019-09-12 15:00 UTC, timwright12 commented on _includes/markdown/React.md
> +When discussing Gutenberg and it's capabilities, we must examine it's role in any given project. Primarily, Gutenberg should be framed as a tool for publishers to manage their content in a more dynam
@magnificode update it's to its

2019-09-12 15:12 UTC, magnificode commented on _includes/markdown/React.md
> +When discussing Gutenberg and it's capabilities, we must examine it's role in any given project. Primarily, Gutenberg should be framed as a tool for publishers to manage their content in a more dynam
:shakesfist: grammar!!

2019-09-12 15:39 UTC, timwright12 commented
@tlovett1 @brentvr This is the first of the Gutenberg PRs if you don't mind putting some eyes on it

2019-09-26 21:34 UTC, timwright12 approved these changes

2019-11-12 13:22 UTC, merged