Adding Spread operator and Rest parameters to JS section
10up/Engineering-Best-Practices pull request #327
Opened 2020-02-07 16:40 UTC by mserino

### Description of the Change
Updating the JavaScript documentation with information about Rest parameters and Spread operators, notation available with ES6.

### Alternate Designs

### Benefits
Additional information that can be referenced for specific ES6 features.

### Possible Drawbacks
May not include all scenarios

### Verification Process

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

### Changelog Entry

2020-02-07 16:43 UTC, timwright12 requested changes

2020-02-07 16:43 UTC, timwright12 commented on _includes/markdown/JavaScript.md
> +The notation `...` which comes with ES6 represents the **spread** operator and **rest** parameters.
@mserino can we focus this more so on the "why" and "when" for using the spread operator. Something like answering the question or "When is it a best practice to use this?" For code samples and such we can just link off site to MDN or something

2020-02-07 16:44 UTC, timwright12 commented
Adding @nicholasio to this PR for review

2020-07-23 15:26 UTC, tlovett1 commented
Hey @mserino this is great! Should we also talk about objects (yes, I know arrays are technically objects but I think you know what I mean)?

2021-08-05 15:53 UTC, nicholasio commented
@mserino Thanks for the PR - as mentioned before in this PR's comments. We want to keep the best practices more focused on "why"/"when" instead of getting more technical and teaching how to use a particular JS feature. With that said I'm going to close this one for now

2021-08-05 15:53 UTC, closed without merging